### ISSUE TITLE
Helpful-material page scroll up button

### ISSUE THREAD

**Issue by BennyCarlsson** [lingonsaft/hacktoberfest#1000]
The Scroll upp button in helpful-material page is missing the arrow icon. Redesign it or add the arrow

**Comment by pawansingh972** [comment]
@BennyCarlsson Can I take this?

**Comment by BennyCarlsson** [comment]
@pawansingh972 Go ahead :)

**Comment by BennyCarlsson** [comment]
resolved Good job :)

**Comment by pawansingh972** [comment]
Glad to help :)
