### ISSUE TITLE
font-awesome not loading

### ISSUE THREAD

**Issue by jlapitan** [lingonsaft/hacktoberfest#1021]
Font awesome css file is loaded but font-awesome is not showing on footer icons(social media accounts)

wrong css class assigned

**Comment by BennyCarlsson** [comment]
now it doesn't work in the sidebar :/

**Comment by pawansingh972** [comment]
It is because of this commit 

ed02c31c30b2ca2dac7d9f06bab9f95f1709a1bd

**Comment by pawansingh972** [comment]
@jlapitan you should have changed this one too

https://github.com/jlapitan/hacktoberfest/blob/f97e05e11738358fdc8d700ef37c7e30e4dd85d9/index.html#L113

as

`	<div class="icon-bar">
  		<a href="https://twitter.com/lingonsaft1" class="twitter icons"><i class="fab fa-twitter"></i></a>
  		<a href="https://www.instagram.com/lingonsaftofficial/" class="insta icons"><i class="fab fa-instagram"></i></i></a>
  		<a href="https://youtube.com/lingonsaft" class="youtube icons"><i class="fab fa-youtube"></i></a>
	</div>`
