### ISSUE TITLE
Add Microsoft hacktoberfest participation

### ISSUE THREAD

**Issue by jlapitan** [lingonsaft/hacktoberfest#1033]
Add a shout-out or call to action button regarding the participation of Microsoft on hacktoberfest.

- https://open.microsoft.com/2018/09/18/hacktoberfest-2018-microsoft/
- https://open.microsoft.com/2018/09/30/join-hacktoberfest-2018-celebration-microsoft/
- https://opensource.microsoft.com/

> If you make at least one pull request* on any Microsoft repo between October 1st – 31st, you’ll receive a limited edition t-shirt designed by Ashley McNamara (Cloud Developer Advocate and graphic designer).

> Yes, really! Any pull request. Please keep in mind the spirit of open source, meaningfully improve projects or documentation, and be kind to the project maintainers and your fellow contributors and community members.

![tshirt design](https://open.microsoft.com/wp-content/uploads/2018/09/Hacktoberfest-Blog.jpg)

More shirt = more fun!!!

**Comment by BraydenChumbley** [comment]
Pull request to solve this has been submitted. Just needs to be merged now.

**Comment by richie-south** [comment]
@BraydenChumbley Could you link it here? :)

**Comment by BraydenChumbley** [comment]
Pull request is here:

https://github.com/lingonsaft/hacktoberfest/pull/1069

**Comment by parthpandyappp** [comment]
I'll be very delighted to be a part of this contribution.
