### ISSUE TITLE
Github API rate issue, stats comes out to be NaN

### ISSUE THREAD

**Issue by vipulbhj** [lingonsaft/hacktoberfest#1041]
I purpose we replace the stats with a message which indicates such has happened and place a link to the repo. Or default values of some kind can be used. Let me know which one you prefer.

**Comment by jlapitan** [comment]
We need to have github api token

**Comment by richie-south** [comment]
@vipulbhj @jlapitan  Could anybody link a guide for how i can generate this token?

**Comment by frextrite** [comment]
The stats.js file runs on client side right? So why does the API calls exceed 60(limit) and gives NaN?

Technically there should be a single call every page refresh.

**Comment by vipulbhj** [comment]
Actually what's happening is they have already done all the token stuff and everything. So when the stats.js file is loaded on your computer it counts as one hit via there key to github. Say 60 people visit the page. There you go limit reached.

**Comment by vipulbhj** [comment]
This has already been handled by me and is fixed by providing an error message stating that this has happened and a link to github repo. The live site has the updated code now if you want to check that out

**Comment by vipulbhj** [comment]
@christophwong What do you purpose ???

**Comment by vipulbhj** [comment]
@richie-south For next year, we will have a whole 11 months period and we will make more structured changes. Thank you for your appreciation.
