### ISSUE TITLE
Navbar still not showing locally

### ISSUE THREAD

**Issue by BennyCarlsson** [lingonsaft/hacktoberfest#1064]
The menu.js script and menu.json doesn't work when you open index.html locally

I don't want the need to run a server locally for it to work

**Comment by disisisid** [comment]
I can take this.

**Comment by anmol8399** [comment]
I wish to fix the issue.

**Comment by Rahul255** [comment]
i can take this.

**Comment by richie-south** [comment]
Should be fixed in #1101
