### ISSUE TITLE
Inconsistent gaps between items on contributors page

### ISSUE THREAD

**Issue by mateossh** [lingonsaft/hacktoberfest#1082]
When someone's name is longer than 1 line, there's weird gap between items.

![2018-10-08-t-screenshot](https://user-images.githubusercontent.com/17083034/46589064-36047600-ca95-11e8-8ffd-f6cdf11736b1.png)

**Comment by Oluwasetemi** [comment]
what do you think can be done to solve the problem!!

**Comment by stalsania** [comment]
Hi,
Is this issue already resolved? I see it fixed on live site.
![image](https://user-images.githubusercontent.com/25429050/46593819-7ba05d80-caec-11e8-9edb-43da5deecf72.png)

Thanks!

**Comment by mateossh** [comment]
I already fixed this issue

PR: #1084

**Comment by richie-south** [comment]
Fixed: closing
