### ISSUE TITLE
Icon in "subscribe" button has weird margin

### ISSUE THREAD

**Issue by mateossh** [lingonsaft/hacktoberfest#1083]
Title is self-explanatory. Screenshot below
![2018-10-08-t-screenshot](https://user-images.githubusercontent.com/17083034/46589169-423d0300-ca96-11e8-8076-399d971ff920.png)

**Comment by dennydap** [comment]
Looks like I can get it fixed. Hold up

**Comment by mateossh** [comment]
I already fixed this issue

PR: #1084

**Comment by dennydap** [comment]
> I already fixed this issue
> 
> PR: #1084

Sorry, it was labeled as open in the hacktoberfest. Thought it wasn't done yet :)

**Comment by richie-south** [comment]
Looks like this is fixed :) closing
