### ISSUE TITLE
Mobile design. Youtube video to big

### ISSUE THREAD

**Issue by BennyCarlsson** [lingonsaft/hacktoberfest#112]
On smaller devices the width on the youtube video is to big on the frontpage.

**Comment by icy-meteor** [comment]
Looks fine to me.

**Comment by BennyCarlsson** [comment]
Aha looks like the video is not to big anymore but still horizontal scrolling on front page

**Comment by uditwapt** [comment]
> On smaller devices the width on the youtube video is to big on the frontpage.

Can i try to work on it? I m very newbie on this same. If you allow i would like to try once.

**Comment by richie-south** [comment]
@uditwapt Yes go ahead 🐝

**Comment by BennyCarlsson** [comment]
Think this is now fixed in one of the pr's will close this. If the problem still exists I will create another more up to date issue because now it's not the youtube video that is the problem
