### ISSUE TITLE
Highlight active nav bar item

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#1138]
When you are on `home`, `helpful material` or `Contributors` the nav bar item should be highlighted somehow

**Comment by TomerPacific** [comment]
Hello,
if anyone hasn't taken this issue yet, I would like to. I would also appreciate any pointers you have in respect to the design (look and color) of the highlighted nav bar items.
Thanks

**Comment by TomerPacific** [comment]
Created a [PR](https://github.com/lingonsaft/hacktoberfest/pull/1188)
