### ISSUE TITLE
The footer blocks Guides list on helpful-material page

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#121]
Add some margin to the bottom of helpful-material to fix this 🥇

**Comment by emorraa** [comment]
Hi, can I take and fix this issue?

**Comment by richie-south** [comment]
@emorraa Yes go ahead! 😃

**Comment by emorraa** [comment]
Thank you, I'm a newbie, hope that I'll fix that! :-)

**Comment by uditwapt** [comment]
@emorraa can i try also on the same issue ?

**Comment by emorraa** [comment]
for sure.

**Comment by emorraa** [comment]
I see that someone added some <br>. Is this accepted? :/

**Comment by emorraa** [comment]
@richie-south Hey, in what sense I have to add an Image? []((https://github.com/lingonsaft/hacktoberfest#contribution-rules))
