### ISSUE TITLE
Highlight active nav bar item

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#1299]
Would be awesome if the active navbar item was highlighted so you know where you are 👀 🕵️‍♀️

**Comment by simpslandyy** [comment]
I'd like to try this one, what do you mean by highlighted?

**Comment by richie-south** [comment]
@simpslandyy Looked at it and left a comment 👍 

Update: We have styles but i don't think it is in use anywhere, so issue is still up for grabs :)
