### ISSUE TITLE
Footer should be the same across pages

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#1348]
We like the footer in `index.html` could we get the same one in `helpful-material.html` and `contributors.html` 👷‍♀️

**Comment by Rahul-Vijay** [comment]
I will work on this

**Comment by richie-south** [comment]
@Rahul-Vijay Yeaay 😃

**Comment by iamxlr8** [comment]
Willing to work on this @richie-south .

**Comment by GabiLea** [comment]
Can i work in this issue?

**Comment by PatriziaT** [comment]
Can I work on this?
