### ISSUE TITLE
Add Other Free Stuff

### ISSUE THREAD

**Issue by JSmurf** [lingonsaft/hacktoberfest#1398]
Add a section detailing other opportunities to get free things, (Microsoft, Sendgrid, etc), so that others can find more opportunities to get shirts/stickers/etc.

**Comment by GiorgioW** [comment]
I think I'm taking it!

**Comment by JSmurf** [comment]
Great! Maybe it'd be best to set up a page, and then people can add other things if they come up later in the month?
