### ISSUE TITLE
Too many pages?

### ISSUE THREAD

**Issue by BennyCarlsson** [lingonsaft/hacktoberfest#1434]
We have a lot of pages under "other" and a lot of pages that's not even in the navbar.

Any ideas how we should filter this?

**Comment by viditvarshney** [comment]
@BennyCarlsson I think , We can make a new folder or a html page which is links to the main "Others" tag ,
and give all the links to the new HTML page or Folder

**Comment by BennyCarlsson** [comment]
@viditvarshney Yes that is one option. We are also considering removing all pages to get a "fresh start" :)

**Comment by Nitrocoder** [comment]
I'll take it on.
