### ISSUE TITLE
Random emoji drop

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#1436]
On the index.html page it currently drops lots of 🥚's, could we randomise an emoji for every drop?

**Comment by ijoosong** [comment]
Hi! My father @hogusong wanted to give this a shot for hacktoberfest!

**Comment by richie-south** [comment]
@ijoosong @hogusong I'm sorry looks like i merge a fix before reading this 😢

**Comment by ijoosong** [comment]
ah shoot okay.  Any other low hanging fruit you can see here? :)
