### ISSUE TITLE
Move tools.html page to navbar

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#1438]
`tools.html` should be inte the navbar **not** under `other` 🔧

**Comment by mbrandon32** [comment]
Ill take a look at it

**Comment by Xol** [comment]
I'd like to make a counter proposal: Maybe tools would fit better under "Helpful Material"?

**Comment by richie-south** [comment]
@Xol I like that idea but i think the `helpful material` page would get to crowded 🤔

**Comment by mbrandon32** [comment]
It already does look crowded on there.   Do we feel it has enough content to warrant its own button?

**Comment by richie-south** [comment]
@mbrandon32 Hum you might be right, Maybe if we remove the `2018` word we get a little more space? :) 

Here we have the [live link of a pull request](https://lingonsaft-hacktober-ryggolddyf.now.sh/) that moves tools to a separate button what do you all think?

**Comment by mbrandon32** [comment]
I think that it looks to fit pretty well.  Removing 2018 would give us more room.  We could also look to decrease the space between the buttons as well.

**Comment by mbrandon32** [comment]
Sorry little slow navigating around here still

**Comment by Xol** [comment]
> @Xol I like that idea but i think the `helpful material` page would get to crowded thinking

Maybe with an custom accordion component[1] we could organize everything a bit better and save some space. But I'm not sure if its a good looking solution, though. :smile: 

[1]https://getbootstrap.com/docs/4.1/components/collapse/#accordion-example

**Comment by richie-south** [comment]
I merged the solution, but i think we should open an issue to remove `2018` and maybe decrease space a little bit :) Would anyone want to create that issue? 🥇

**Comment by richie-south** [comment]
@Xol If you have time to submit a pull request so we can se a live example of this? :)

**Comment by Xol** [comment]
> @Xol If you have time to submit a pull request so we can se a live example of this? :)

I'm on it. :+1:

**Comment by Xol** [comment]
> @Xol If you have time to submit a pull request i would like to see a live example of this? :)

#1470 My take on reorganizing the content with an accordion. If it's useful, we could take the content from _tools.html_ to the _Helpful Material_ site.
