### ISSUE TITLE
Disable drop.js functions when using mobile 

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#1449]
Drop.js could cause lagg on mobile devices could we disable it when browsing with small screens :)

**Comment by ijoosong** [comment]
Sounds like something @hogusong can try!

**Comment by TremaineNeethling** [comment]
@richie-south Is this still open? i would love to work on this.
What is the minimum screen width at which you want to make it rain? :)

**Comment by Hogusong** [comment]
I am making PR right now.

**Comment by BennyCarlsson** [comment]
Good job :)
