### ISSUE TITLE
Migrate site to a static generator

### ISSUE THREAD

**Issue by kwaimind** [lingonsaft/hacktoberfest#145]
Suggest we move the site to something like [pugjs](https://pugjs.org/api/getting-started.html) to handle templates and basic layouts. As this site develops things like consistent menu links, content blocks, and more are being left behind :(

Will need some tweaks to the build process too so the repo is compiled and then uploaded to the server.

I'm happy to do the template stuff. Will need help for the server build process 🐶

**Comment by BennyCarlsson** [comment]
Hmm will this add a build step? Because it's important that we keep the project simple so that anyone can work on it. The most important part is that if you clone the project the only thing you need to do is open index.html to make it work :)

**Comment by kwaimind** [comment]
Yeah that's true. It will add a build step yes and probably a gulp watch or something to keep compiling as you save. 

Ok, scrap it. One for the future maybe. I'll close the task.
