### ISSUE TITLE
Add subtitles to videos

### ISSUE THREAD

**Issue by BBhargavB** [lingonsaft/hacktoberfest#1530]
Subtitles will help to understand,what's saying in the video clearly.

**Comment by enriquezm** [comment]
Would this be in the form of a transcript? Or subtitles to the original video source?

**Comment by swastikbanerjee07** [comment]
Can you please elaborate on the issue?
Which video?

**Comment by enriquezm** [comment]
@swastikbanerjee07 I believe it's the videos on the main README of the repo:
[Hacktoberfest Intro](https://youtu.be/OsAFX_ZbgaE)
[How to pull request Overview](https://youtu.be/DIj2q02gvKs)
[Merge Conflict / comment](https://youtu.be/zOx5PJTY8CI)

**Comment by CQW-Code** [comment]
I don't know exactly what they want but can tell you that 1. Transcript is good. 2. Subtitles or "open captions" even better but the captions would always be visible (not a bad thing) 3. Youtube does auto captions and you then can edit the file that's created to fix errors etc; I don't know if they're closed captions (able to toggle on and off).  
-- From a user who uses captions every day (when they're available...)

**Comment by enriquezm** [comment]
@CQW-Code I wanted to edit the auto captions that Youtube generates, but I believe the video needs to be editable. Actually, I think I would need access to the edit screen on their youtube account?

**Comment by CQW-Code** [comment]
yes you'd probably need access to their account, the other way is for whoever 'owns' the video can download the text file and send it to you.   Maybe the suggestions here may help (notably the video?).  https://www.quora.com/How-do-I-download-auto-generated-subtitles-in-YouTube
