### ISSUE TITLE
Fix duplicated content in Helpful Material section

### ISSUE THREAD

**Issue by jclopezdev** [lingonsaft/hacktoberfest#1612]
There are duplicated sections on the `Helpful material` page like `Additional Projects` and `Helpful Links`

<img width="1113" alt="screenshot 2018-10-12 08 49 29" src="https://user-images.githubusercontent.com/1099323/46873268-c3302d80-cdfb-11e8-92aa-d522d136c5b1.png">

<img width="1112" alt="screenshot 2018-10-12 08 50 18" src="https://user-images.githubusercontent.com/1099323/46873328-dc38de80-cdfb-11e8-93a2-df57412e220d.png">

**Comment by jclopezdev** [comment]
Working on it

**Comment by msatul1305** [comment]
done 👍

**Comment by BennyCarlsson** [comment]
Great
