### ISSUE TITLE
Labels for "other projects" list items in "helpful material" page 

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#172]
Add difficulty label's (easy, medium, hard) for "Other Projects" list items so people can know the level of difficulty to contribute to that project. Each project should be able to have multiple labels ex: easy and medium.

**Comment by WanielDeiss** [comment]
I'll can do that! can i pick it up?

**Comment by richie-south** [comment]
@WanielDeiss Yes of course 😃

**Comment by BennyCarlsson** [comment]
closing this issue and opening a new one because I don't want easy-medium-hard
