### ISSUE TITLE
Add Navbar and a footer 

### ISSUE THREAD

**Issue by CleverFool77** [lingonsaft/hacktoberfest#18]
Currently the website lacks proper navbar and footer,It will look better if we can add both.

**Comment by richie-south** [comment]
Great idea!

**Comment by sigiasd** [comment]
Working on it. Will be my first ever Github Work :D

**Comment by pvn6396** [comment]
#32 **pull request** 
Added a collapsible navbar with styling

**Comment by sigiasd** [comment]
#36 
Tried doing it in the style of the site

**Comment by itsVagabond** [comment]
#63 Tried doing some styling
