### ISSUE TITLE
Remove styles from index.html

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#1831]
Move all styles inside `index.html` to separate files 👍

**Comment by mpaarating** [comment]
I'll snag this one if thats ok!

**Comment by rohit21p** [comment]
it's still open, should I do it?

**Comment by mpaarating** [comment]
@rohit21p I have a PR up for it. Once its merged the `css/index.css` file could use a lot of organizing :D

**Comment by bloqhead** [comment]
I'd be happy to pitch in here if needed but it seems like you guys have a handle on it.

**Comment by richie-south** [comment]
I think this is fixed now :) If not tell me 😉
