### ISSUE TITLE
Cannot make pull request

### ISSUE THREAD

**Issue by AleSpreafico** [lingonsaft/hacktoberfest#1837]
sorry to bother
this is actually my first pull request ever xD

I did everything: Cloned the repo, than create my  custom-branc, than try to commit my changes.
But it says I do not have permission to push those changes!
how cane I do?

**Comment by Jonathan-Montanez** [comment]
Did you fork the repo?

**Comment by Jonathan-Montanez** [comment]
Did you merge your branch with the master?

**Comment by AleSpreafico** [comment]
`git clone https://github.com/lingonsaft/hacktoberfest.git Hacktober'
`cd Hacktober'
'git checkout -b button-branch'
then I did my changes (created html, css ....)
`git add .
git commit -m "My message"
git push origin button branch`

this is what id did and right after I got that problem

**Comment by Jonathan-Montanez** [comment]
it seems you did not merge your changes

**Comment by AleSpreafico** [comment]
soved.... I didnt Forked it!! Thanks You helped me on my first pull ever!!! =)
