### ISSUE TITLE
homepage is messed up

### ISSUE THREAD

**Issue by cTxplorer** [lingonsaft/hacktoberfest#1896]
| Issue | Solution |
| ------: | :-------- |
| Speedy animations | Slow down falling objects' speed |
|  | Slow down title's shaking speed |
| Too many objects | Reduce number of falling objects |
| Very dark background gradient | Change gradient to something lighter in color and easy on eye |

**Comment by db586jf** [comment]
I'll try it if I can

**Comment by ShubhanshuGairola** [comment]
i hope these changes would be appropriate corresponding to this issue

**Comment by cTxplorer** [comment]
@ShubhanshuGairola there's some glitch in animations - objects are lagging in my movile device. Also, can you fix second issue?

**Comment by cTxplorer** [comment]
Good work till now!

**Comment by ShubhanshuGairola** [comment]
I have tried to remove the glitch in animation of title

**Comment by ShubhanshuGairola** [comment]
this might remove the glitch

**Comment by cTxplorer** [comment]
@ShubhanshuGairola looks good to me, send a PR!

**Comment by ShubhanshuGairola** [comment]
#1943 
I recently made a commit

**Comment by vyaspranjal33** [comment]
@BennyCarlsson i Think the project is messed :confused:
