### ISSUE TITLE
Change colour of button and text Start Hacking to Color which is compatible with fire emoticon

### ISSUE THREAD

**Issue by CleverFool77** [lingonsaft/hacktoberfest#193]
The fire emoticon is gradient Color of three or more..which isn't compatible with the currently existing button Color.It would be better to go with complementary Color.

**Comment by Vishal1541** [comment]
I would like to take this issue. :)

**Comment by coderhawk999** [comment]
added new look for button "hacktober fest look"
@lingonsaft look into #234

**Comment by BennyCarlsson** [comment]
closing this issue for now :)
