### ISSUE TITLE
Delete pages!

### ISSUE THREAD

**Issue by BennyCarlsson** [lingonsaft/hacktoberfest#2030]
I think we have to many pages. **Please only delete 1 page per pull request**

Delete pages that are not working.

Delete pages that are not in any menu

Delete pages that are unnecessary

**Comment by MoyinShabi** [comment]
Can I try this?

**Comment by Nisinghal** [comment]
Willing to work on this!

**Comment by pydevsg** [comment]
Sir, can I work on this project.Is it open now?

**Comment by pydevsg** [comment]
Sir, I am working on it.
Will reach you soon with a pull request debugging the errors and resolving your issues.

**Comment by pydevsg** [comment]
Sir,please check my pull request and merge it if found valuable.

**Comment by richie-south** [comment]
@pydevsg great work :D

**Comment by pydevsg** [comment]
Thanks @richie-south

**Comment by pydevsg** [comment]
Here's the next pull request which I founded as a bug in the file ,please do see the update and merge it if found useful.

**Comment by pydevsg** [comment]
SIr, I am trying my best to make this project bug free removing damage files. Hope you all like it.

**Comment by ramkrishn123** [comment]
I like to contribute to this project.

**Comment by Abhishake1999** [comment]
I like to contribute to this project.

**Comment by brunonepomuceno** [comment]
#2438 👍

**Comment by lstravers** [comment]
2457 ✅
