### ISSUE TITLE
Page is totally broken :(

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#2108]
Anybody know why?

**Comment by albanmahmut** [comment]
> Looks like it was this commit that destroyed everything
> 
> [547e119](https://github.com/lingonsaft/hacktoberfest/commit/547e119165ae06ba19827f5cefd330e3c629d0c7)

får jag titta på detta?

**Comment by richie-south** [comment]
@albanmahmut yes 👍

**Comment by albanmahmut** [comment]
> @albanmahmut yes

Ok, Lets see if we can find the solution.

**Comment by NitinNair89** [comment]
Which page has the issue? Is this solved?

**Comment by BennyCarlsson** [comment]
@NitinNair89 I think this is solved forgot to close this :)
