### ISSUE TITLE
Move invert from navbar

### ISSUE THREAD

**Issue by BennyCarlsson** [lingonsaft/hacktoberfest#2171]
In the **Navbar** under **other** you will find invert. Remove invert from there and make it into a button on index.html

**Comment by telenord** [comment]
@BennyCarlsson Hi, I ready to solve it

**Comment by biswaroop1547** [comment]
Sorry but I only found a link to an invert.js file in index.html, can you explain a little more what to change? 
I am super new to open source.

**Comment by biswaroop1547** [comment]
@BennyCarlsson I just created a pull request for this #2254
please check if I am wrong anywhere, thanks!

**Comment by biswaroop1547** [comment]
#2254

**Comment by biswaroop1547** [comment]
#2254

**Comment by BennyCarlsson** [comment]
Great work :)

**Comment by vyaspranjal33** [comment]
@BennyCarlsson  #2254  seems its not fixed
![image](https://user-images.githubusercontent.com/11768143/47418205-460b9d80-d797-11e8-9e3f-66e94f900af3.png)

**Comment by vyaspranjal33** [comment]
:+1:
