### ISSUE TITLE
social icons style

### ISSUE THREAD

**Issue by vyaspranjal33** [lingonsaft/hacktoberfest#2246]
Footer css should be same on all page right now social icons deafault behavoiur is black & on:hover it turns in to pink .. while helpful-material.html & contributors.html page social icon deafault behaviour is green & on:hover it turns in to sky blue
![image](https://user-images.githubusercontent.com/11768143/47340894-3750b800-d6bd-11e8-97d0-4b43c5db6ae9.png)

![image](https://user-images.githubusercontent.com/11768143/47340925-4cc5e200-d6bd-11e8-9fa5-c554f0d778e8.png)

**Comment by NitinNair89** [comment]
Add the common style for footer's social media icons in footer.css. Which style do you prefer to keep - Black or Green?

**Comment by BennyCarlsson** [comment]
@NitinNair89 you can change to any color as long as it's consistent on all pages :)

**Comment by vyaspranjal33** [comment]
@NitinNair89  i think black would be good

**Comment by NitinNair89** [comment]
> 
> 
> @NitinNair89 i think black would be good

Just plain black? Or Black and white toggle on hover? I feel black and white toggle would support the surrounding text

**Comment by vyaspranjal33** [comment]
@NitinNair89  black and pink toggle on hover

**Comment by iamj4james** [comment]
@vyaspranjal33 I would Like to take on this issue

**Comment by vyaspranjal33** [comment]
@iamj4james  go ahead

**Comment by nicehatharry** [comment]
Looks like somebody got creative with these, but they're all pink all the time! Mind if I change them to be black / pink on hover?
