### ISSUE TITLE
Formatting of html

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#248]
Format html

This will probably create a lot of conflicts with other pull request but it is something that has to be done

**Comment by nmcateer** [comment]
I'd be interested in helping with this. Is there any specific formatting guidelines you would like the HTML to follow for this?

**Comment by richie-south** [comment]
@nmcateer I like 2 spaces... But no i don't know any html formatting guidelines. 
Maybe we should write one down in the README file?

**Comment by nmcateer** [comment]
2 spaces sounds good to me. Yes writing a short guide in the README might be beneficial - we could make a summarised outline of the W3 schools (https://www.w3schools.com/html/html5_syntax.asp) style guidelines? I can take this on as part of the formatting if desired.

**Comment by richie-south** [comment]
@nmcateer You are the main person on this now!

**Comment by praveen-me** [comment]
Can I work on it?

**Comment by nmcateer** [comment]
I'm afraid i have already made a pull request for this issue, but i'm sure there are some others on the list of issues that the project owner would love to have your help on @praveen-me !

**Comment by BennyCarlsson** [comment]
This is done for now
