### ISSUE TITLE
Formatting css

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#250]
This will probably create a lot of conflicts with other pull request but it is something that has to be done

**Comment by PallaviDas07** [comment]
I am interested.

**Comment by richie-south** [comment]
@PallaviDas07 Then go ahead 👍

**Comment by praveen-me** [comment]
Can I work on this?

**Comment by richie-south** [comment]
@praveen-me off course :)

**Comment by focux** [comment]
@richie-south  By that you mean to prettify the code? If so, would you want a prettier config file to be include?

**Comment by BennyCarlsson** [comment]
Think this have been fixed for now
