### ISSUE TITLE
Remove inline javascript

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#251]
Move all inline javascript to separate .js files

**Comment by mohammad-aliB** [comment]
Hi I’m interested in the issue, when would I have to get this done by as I’m at schoool then work for the next 8 ish hours

**Comment by Broccolai** [comment]
I'm going to work on this if thats okay

**Comment by richie-south** [comment]
@mohammad-aliB At this rate this issue is probably resolved within the next hour. But when you get back their are probably new issues 😄

**Comment by richie-south** [comment]
@Broccolai i should close this now right?

**Comment by Broccolai** [comment]
Yep! Close it :)

**Comment by Broccolai** [comment]
Oh, and assign me and the other guy that worked on it 👍

**Comment by richie-south** [comment]
@Broccolai What do you mean with assign? How do i do that 🚶

**Comment by Broccolai** [comment]
Don't worry, I forgot this was github and not gitlab. My bad 😛
