### ISSUE TITLE
Menu links don't work

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#252]
The links in the top menu seams to have broken

**Comment by marataziat** [comment]
Have you also this error: https://prnt.sc/l1bycq ?

**Comment by richie-south** [comment]
Yes. I think the links shouldn't have .html in them but i don't know.

**Comment by AraanBranco** [comment]
I already have an idea how to solve

**Comment by richie-south** [comment]
@AraanBranco Great! This is critical to the site

**Comment by AraanBranco** [comment]
See https://github.com/lingonsaft/hacktoberfest/pull/260 =)
