### ISSUE TITLE
Social links always visible 

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#254]
I think we should make the social links in the footer always visible instead of hidden behind a mouse press

**Comment by LinaJohnson** [comment]
@richie-south I'd be happy to take this one.

**Comment by richie-south** [comment]
@LinaJohnson Wouldn't have it any other way 😀

**Comment by parthpandyappp** [comment]
I'll like to contribute to this issue.!

**Comment by LinaJohnson** [comment]
@richie-south PR is open and available for review here: https://github.com/lingonsaft/hacktoberfest/pull/267
