### ISSUE TITLE
Service worker should update on page refresh

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#270]
Can we get the service worker to update on new page loads? I'm always getting an older cached version of the site after i reload.

**Comment by 3daddict** [comment]
I am having a similar issue. I'll look into it.

**Comment by richie-south** [comment]
Merged a fix for this :) Hopefully we can close this sone!

**Comment by 3daddict** [comment]
Looks like the fixed worked!

**Comment by BennyCarlsson** [comment]
Good job closing this :)
