### ISSUE TITLE
Footer is to big at the moment

### ISSUE THREAD

**Issue by BennyCarlsson** [lingonsaft/hacktoberfest#286]
Change design on footer is to big and wrong color at the moment :)

**Comment by Broccolai** [comment]
Working on it!

**Comment by CruiseDevice** [comment]
Can you please elaborate on what color to use and how big it should be.

**Comment by richie-south** [comment]
@CruiseDevice It should be the same as the header menu :)

**Comment by BennyCarlsson** [comment]
Good job :)
