### ISSUE TITLE
Add Easter Eggs!

### ISSUE THREAD

**Issue by BennyCarlsson** [lingonsaft/hacktoberfest#291]
🥚

**Comment by sagarchoudhary96** [comment]
@BennyCarlsson can you tell what we can do in this

**Comment by BennyCarlsson** [comment]
@sagarchoudhary96  I don't know maybe a secret message in the consolelog ;)

**Comment by aayushbisen** [comment]
Hello sir , this is interesting.
Can I do this?

**Comment by richie-south** [comment]
@aayushbisen Yes this is an forever open issue so go ahead

**Comment by jaredstevick** [comment]
this sounds fun. i'll see what i can do.

**Comment by marekgebka** [comment]
Awesome! On it!

**Comment by MADPT** [comment]
Nice, I'll create something. Muahahah

**Comment by MADPT** [comment]
Here you go #355

**Comment by BennyCarlsson** [comment]
Seems like we got a few easter eggs in ;) You can keep doing them or fix mere conflicts in your pull requesta and we will merge them. Closing the ticket for now :)
