### ISSUE TITLE
Social media links are hard to se in the footer

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#298]

**Comment by kev1nboer** [comment]
@richie-south I can pick this up. Anything you had in mind for the icons?

**Comment by richie-south** [comment]
@kev1nboer Yes

**Comment by kev1nboer** [comment]
> @kev1nboer Yes
Would changing the colour be enough?

**Comment by richie-south** [comment]
@kev1nboer We kinda want the footer to have the same color as the top menu bar

**Comment by kev1nboer** [comment]
@richie-south Alright, so changing the colour on the icons to white would be OK?

**Comment by richie-south** [comment]
@kev1nboer Yes sounds smart 👍

**Comment by kev1nboer** [comment]
OK! Im on it!

**Comment by kev1nboer** [comment]
@richie-south #308 Added a pull request!

**Comment by BennyCarlsson** [comment]
merged the pull request
