### ISSUE TITLE
Subscribe to youtube button?

### ISSUE THREAD

**Issue by BennyCarlsson** [lingonsaft/hacktoberfest#303]
We will make a timelapse video when this over :) people need to see it. Maybe add a subscribe to our youtube channel button?

**Comment by LinaJohnson** [comment]
@bennycarlsson I can take this one!

**Comment by richie-south** [comment]
@LinaJohnson Ofc, Go ahead :D

**Comment by LinaJohnson** [comment]
@richie-south PR is available for review here: https://github.com/lingonsaft/hacktoberfest/pull/359
