### ISSUE TITLE
Change contributor cards to links

### ISSUE THREAD

**Issue by NehemiahK** [lingonsaft/hacktoberfest#326]
The whole contributor card would be better if it was a link.

**Comment by Crazzi-Boii** [comment]
I had removed the whole card and add a template such that it will generate different cards in 3 columns and multiple rows.

PR #224

**Comment by Crazzi-Boii** [comment]
until and unless mainteners merge my code ppl will use the single card.

**Comment by richie-south** [comment]
Closing this for now :)
