### ISSUE TITLE
Routes on index page and contributions

### ISSUE THREAD

**Issue by ryanlsmith4** [lingonsaft/hacktoberfest#343]
I fixed the dead routes on the index and contributions page! Im still kinda new how do i push for you to verify and merge?

**Comment by ryanlsmith4** [comment]
remote: Permission to lingonsaft/hacktoberfest.git denied to ryanlsmith4. << this is my error

**Comment by Pluppen** [comment]
@ryanlsmith4 https://youtu.be/DIj2q02gvKs

**Comment by richie-south** [comment]
Closing this for now
