### ISSUE TITLE
Footer Nav "Social Links" is looking messed up !

### ISSUE THREAD

**Issue by lazycipher** [lingonsaft/hacktoberfest#407]
Issue :  Footer Social Links Looks different on Homepage
https://imgur.com/a/gfJn9ee

I would Like to work on this!

**Comment by Broccolai** [comment]
Honestly maybe we should do something floating on the side of the page for social links, we're taking up a lot of room for them.

Maybe something like this?
![image](https://user-images.githubusercontent.com/28634904/46399351-59bf6900-c6ef-11e8-85c1-d5a2dcffa14f.png)

I'd be willing to take a crack at it if you'd want something more like this. 😄

**Comment by mufti1** [comment]
> Honestly maybe we should do something floating on the side of the page for social links, we're taking up a lot of room for them.
> 
> Maybe something like this?
> ![image](https://user-images.githubusercontent.com/28634904/46399351-59bf6900-c6ef-11e8-85c1-d5a2dcffa14f.png)
> 
> I'd be willing to take a crack at it if you'd want something more like this.

so change the icon or just fix footer? maybe can open issue to change icon

**Comment by lazycipher** [comment]
> ![image](https://user-images.githubusercontent.com/20008670/46398912-95265b80-c720-11e8-999d-52c99bea1f04.png)
> 
> like this?

Yup !! It's now showing up on website as of now !!

**Comment by mufti1** [comment]
> > ![image](https://user-images.githubusercontent.com/20008670/46398912-95265b80-c720-11e8-999d-52c99bea1f04.png)
> > like this?
> 
> Yup !! It's now showing up on website as of now !!

just check my pull request i have fixed it

**Comment by richie-south** [comment]
Hey i like that side bar thing 👍 Could someone try that and make a pull request?

**Comment by richie-south** [comment]
@mufti1 Could you link you pull request here?

**Comment by mufti1** [comment]
> @mufti1 Could you link you pull request here?

my PR is merged now

**Comment by mufti1** [comment]
![image](https://user-images.githubusercontent.com/20008670/46400104-c7858800-c723-11e8-9c23-017324d4de7e.png)
why footer change again? anyone change this?

**Comment by richie-south** [comment]
@mufti1  Looks fine for me! It might be cache, try opening the page in incognito :)

**Comment by richie-south** [comment]
Think we should remove the service worker that caches the page or make so that it updates on every page reload

**Comment by BennyCarlsson** [comment]
@mufti1 Took a while for me to get the update. Try inkognito mode

**Comment by mufti1** [comment]
> @mufti1 Looks fine for me! It might be cache, try opening the page in incognito :)

i see thankyou bro but i forgot to add my profile in contributor :D can i pull request this?

**Comment by richie-south** [comment]
Closing this issue :) Think we should open a new one about service worker removal / cache fix do

@mufti1 Yes of course!

**Comment by mufti1** [comment]
> Closing this issue :) Think we should open a new one about service worker removal / cache fix do
> 
> @mufti1 Yes of course!

@richie-south can merge my pull request in contributing.html?
