### ISSUE TITLE
Making the site 100% mobile friendly - report issues

### ISSUE THREAD

**Issue by Broccolai** [lingonsaft/hacktoberfest#414]
I’m going to be working on this after class.
So far I’ve got 

- home page has too much width allowing for mobile users to scroll horizontally 
- cheese page is completely broken

Add anything I’ve missed and I’ll fix it soon 😄

**Comment by richie-south** [comment]
You are a 👑 You should be prepared for lots of conflicts by then 😊

**Comment by Broccolai** [comment]
Can’t wait :’)

**Comment by Broccolai** [comment]
Laptop is about to die and I don't have my charger but, index.html has been fixed with #436

**Comment by BennyCarlsson** [comment]
@Broccolai Oh I see :P

**Comment by BennyCarlsson** [comment]
Are you still working on this @Broccolai  ??

**Comment by richie-south** [comment]
We have been updating the page a lot so closing this issue for now, but feel free to continue your work if you want to 👍
