### ISSUE TITLE
Grammatical errors on helpful material page

### ISSUE THREAD

**Issue by Myles2** [lingonsaft/hacktoberfest#419]
I would like to fix certain grammatical errors on the helpful material page.

**Comment by richie-south** [comment]
Spelling is not my strong side so go ahead 👍

**Comment by Myles2** [comment]
I was able to fix some of the grammatical errors but when I try to push the commit I get an error: 403 does anyone know why?

**Comment by richie-south** [comment]
Watching this video might help ⛑ https://www.youtube.com/watch?v=DIj2q02gvKs&feature=youtu.be

**Comment by Myles2** [comment]
Thanks for the link I've watched that video quite a few time it was helpful! But my problem ended up being that since I had forked the Hacktoberfest project on your personal page previously it wouldn't let me fork the new one which in turn stop me from commiting or pushing anything to the new one. But I finally figured it out!

**Comment by richie-south** [comment]
@Myles2 We merged you fix right? 😃
