### ISSUE TITLE
Duplicate URLs in helpful material's Guide section

### ISSUE THREAD

**Issue by ApoTheOne** [lingonsaft/hacktoberfest#421]
Duplicate [URLs](https://github.com/lingonsaft/hacktoberfest/blob/d85c2efb0513fc034ee15b4ca68d26d9549d98bd/helpful-material.html#L132) in helpful material's Guide section:

https://github.com/lingonsaft/hacktoberfest/blob/d85c2efb0513fc034ee15b4ca68d26d9549d98bd/helpful-material.html#L136

**Comment by darshan934** [comment]
Can I work on this issue? Only the duplicate URLs need to be taken out from helpful-materiail.html, right?
