### ISSUE TITLE
Service worker cache to strong

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#427]
In my experience service workers are not a good fit for a project that updates multiple times a day. I'm constantly viewing an older version of the site. Is there any way to control how strong the caching is or should we remove it entirely? 🤔

**Comment by sn149** [comment]
Try putting this in your head tags
`<meta http-equiv="cache-control" content="no-cache">`

**Comment by richie-south** [comment]
@sn149 Does this control the Service Worker? If so could you make a pull request with this? 👍

**Comment by sn149** [comment]
i'm not sure :sweat_smile:
