### ISSUE TITLE
[UI] Blue theme, text not clear.

### ISSUE THREAD

**Issue by chamow97** [lingonsaft/hacktoberfest#450]
When we change to Blue theme, the main text is not clear and visible(feeble), may be a bolder text will do I guess.

**Comment by richie-south** [comment]
Do we have a blue theme? 🤣

**Comment by saurabhkoshatwar** [comment]
May i help?

**Comment by saurabhkoshatwar** [comment]
Need any changes

**Comment by chamow97** [comment]
We can change the text to be a bit more bolder.

**Comment by saurabhkoshatwar** [comment]
Done!

**Comment by BennyCarlsson** [comment]
Seemed to be solved. Good job :)
