### ISSUE TITLE
adjust navbar according to adjustable length of browsers and desktops

### ISSUE THREAD

**Issue by CleverFool77** [lingonsaft/hacktoberfest#47]
The navbar is just covering half of the screen in one desktop/browser or going out of bounds in another.Adjust needed

**Comment by richie-south** [comment]
Yes this is critical!

**Comment by Sangatdas** [comment]
Can I use bootstrap?? Or should I only use media queries?

**Comment by richie-south** [comment]
You can use bootstrap if you want 😉
