### ISSUE TITLE
Add a new page

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#483]
We already have `cheese`, `potato`, `Fireworks` (might miss one or two) can we add more pages dedicated to awesome stuff?

**Comment by ronlaniado** [comment]
I'll add a page

**Comment by richie-south** [comment]
@ronlaniado Great :D

**Comment by lomitaswa** [comment]
I wanna help you here.

**Comment by AnitaOlsen** [comment]
I would love to help!

**Comment by jcat1504** [comment]
Can I add a "Cats and Code" page?

**Comment by theREALaltoid** [comment]
@jcat1504 Yes. I support.

**Comment by richie-south** [comment]
@jcat1504 Me to!!

**Comment by mohamedkhaledyousef** [comment]
I can do it

**Comment by BennyCarlsson** [comment]
Seems like we got a lot of new awesome pages :) closing this but feel free to add more
