### ISSUE TITLE
Rearrange video cards in index.html 

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#485]
I think it is better to switch places of the "How to Pull request [Overview]" and "Here are some tips on what to do!" cards. 

So to be clear on the first row we would have "Hacktoberfest Intro" next to "Here are some tips on what to do!" and on the second row have "How to Pull request [Overview]" next to "How to solve merge conflicts"

**Comment by cassadab** [comment]
I'd be happy to work on this one!
