### ISSUE TITLE
More love <3 

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#486]
We have one heart on the index.html page can we show love any where else?

**Comment by 00aney** [comment]
I want to take it.

**Comment by richie-south** [comment]
@00aney Yes :)

**Comment by lomitaswa** [comment]
May i help?

**Comment by AnitaOlsen** [comment]
I would love to help :)

**Comment by BennyCarlsson** [comment]
@AnitaOlsen hehe pun intended?

**Comment by BennyCarlsson** [comment]
Lots of love! ❤️ Keep the love going but closing the issue for now :)
