### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by BennyCarlsson** [lingonsaft/hacktoberfest#5]
The website looks really boring now. It needs some css and styling :)

**Comment by amrs-tech** [comment]
Please assign this to me. I'll try to add more styles.

**Comment by Danishkhan97** [comment]
I am already working on this issue. @amrs-tech @BennyCarlsson

**Comment by BennyCarlsson** [comment]
@amrs-tech @Danishkhan97 The only issue is that merge conflicts might occur that needs to be resolved before a merge. But multiple people can and should work on this issue since styling will never be "done" :)

**Comment by amrs-tech** [comment]
@BennyCarlsson Okay :)

**Comment by richie-south** [comment]
Thanks everyone for the design help! I think we have a solid design base so i'm closing this issue for now. Focus should instead be on getting the other pages up to speed and fixing overall quirks (colors, css buggs, and overall minor design improvements)
