### ISSUE TITLE
Moving Nav bar to external html to remove redundency 

### ISSUE THREAD

**Issue by lmberman** [lingonsaft/hacktoberfest#566]
The Nav bar values are copied in each html. This causes in consistency of links in the nav bar for each page.

I'm working on this now. Stay tuned.

**Comment by lmberman** [comment]
I am closing this because someone already made this change. 

I need help I am having issues pulling the newest code from this repository. Any suggestions?

**Comment by richie-south** [comment]
You could delete your fork and create a new one :) Otherwise check out the videos in the readme file or index.html file :)
