### ISSUE TITLE
Re design ideas 

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#583]
Could we get some redesign examples in this thread, images, pull requests / what ever. How can we make this site extra beautiful? 💅 

This is be open for everybody, you can't claim it 😃

**Comment by jofftiquez** [comment]
Hot pink is too distracting. Visitors might have a hard time focusing on the content.

**Comment by AbidemiT** [comment]
change color from pink to green(#38ce59)

**Comment by BennyCarlsson** [comment]
Closing this for know feel free to keep working on design
