### ISSUE TITLE
Request for OAUTH-TOKEN

### ISSUE THREAD

**Issue by jlapitan** [lingonsaft/hacktoberfest#588]
Need this to add new feature, currently testing via personal token

**Comment by jlapitan** [comment]
on the homepage a script is calling the github api to get stats of the repo

**Comment by BennyCarlsson** [comment]
We will have a look at this and see if we can provide a oauth token :)

**Comment by richie-south** [comment]
As of right now we don't use the Github api on the page, so i'm closing this for now.

**Comment by jlapitan** [comment]
should we user github api? https://github.com/jenkoian/hacktoberfest-checker#running-the-app

**Comment by richie-south** [comment]
@jlapitan It's the smartest idea 😛
