### ISSUE TITLE
The navbar is getting crowded any ideas?

### ISSUE THREAD

**Issue by BennyCarlsson** [lingonsaft/hacktoberfest#592]
All the new pages getting added is making the navbar messy.

My suggestion is to go back to the 3 standard navbars (Home,Helpful-Material, Contribution) and move the other navbars/feature somewhere else? Any suggestions?

**Comment by syauqiahmd** [comment]
may i help you with create a few drop down menu from your navbar menu ?

**Comment by BennyCarlsson** [comment]
@syauqiahmd  Go ahead :)

**Comment by satya-vinay** [comment]
Making drop-downs with sections like Tech, Entertainment,News would help i think.And put new pages into their related section.

**Comment by BennyCarlsson** [comment]
@satya-vinay That sounds like a good idea

**Comment by BennyCarlsson** [comment]
We now have a drop down but only for index.html anyone care to fix it on all the other pages?

**Comment by HJain13** [comment]
Taking this up

**Comment by BennyCarlsson** [comment]
@HJain13 Great looking forward to it ;)

**Comment by syauqiahmd** [comment]
hi @HJain13, I already done that

**Comment by richie-south** [comment]
Awesome 👍
