### ISSUE TITLE
Repetition of Tools at Nav bar contributors.html 

### ISSUE THREAD

**Issue by satya-vinay** [lingonsaft/hacktoberfest#608]
There are two tools in the navbar of contributors.html 

one of them is redirecting to wow.html, so change the name of it.

**Comment by Broccolai** [comment]
Fixed with #609

**Comment by satya-vinay** [comment]
great :+1:

**Comment by yasora099** [comment]
fixed it

**Comment by satya-vinay** [comment]
@Broccolai  @yasora099 Ask before you claim issues,only after claiming it start working on it.
It is standard practice to be followed when you contribute to open source projects.

**Comment by Broccolai** [comment]
Sorry, I had it fixed locally for awhile before I saw this issue :p

**Comment by BennyCarlsson** [comment]
This issue seems to have been solved 3 times so closing it xD
