### ISSUE TITLE
can we ditch twitter bootstrap and use css grid instead? 

### ISSUE THREAD

**Issue by leighayanid** [lingonsaft/hacktoberfest#61]

**Comment by BennyCarlsson** [comment]
Yes feel free to change that :) however leave the bootstrap dependancy if someone uses it for something else ;)

**Comment by BennyCarlsson** [comment]
@leighayanid anyone working on this? feel free to open again if not I will close this

**Comment by leighayanid** [comment]
apologies for the late reply. Yes, I will be working on this :)
