### ISSUE TITLE
Helpful Material href is not working

### ISSUE THREAD

**Issue by DCox2016** [lingonsaft/hacktoberfest#617]
In Nav bar the Helpful Material href is not working. When clicked site is redirects to "Your File was not found".
![screen shot 2018-10-04 at 6 20 49 am](https://user-images.githubusercontent.com/17097992/46468163-afeae580-c79d-11e8-808f-23ac8f54f5e3.jpg)

**Comment by DCox2016** [comment]
I am taking this issue

**Comment by DCox2016** [comment]
Cool I don't have permission to push

**Comment by Broccolai** [comment]
Yeah, you need to fork it then make a pull request

**Comment by DCox2016** [comment]
ah ok thanks

**Comment by BennyCarlsson** [comment]
@DCox2016 Good job fixing this :)
