### ISSUE TITLE
Issue in header vertical alignment

### ISSUE THREAD

**Issue by d3vil0p3r** [lingonsaft/hacktoberfest#625]
Header is not aligned perfectly to top, and also is overlapping over page's content. Here's the issue in action.
![header_issue](https://user-images.githubusercontent.com/4662916/46471754-932fcb80-c7f8-11e8-8c91-469712d8f3a1.gif)

**These issues have to be fixed.**

**Comment by d3vil0p3r** [comment]
I am doing this.

**Comment by Broccolai** [comment]
I've already fixed the overlapping in #609 waiting for a merge

**Comment by d3vil0p3r** [comment]
@Broccolai you haven't address both the issues. Rest is upto the maintainers 👍
