### ISSUE TITLE
Broken nav links from helpful-material.html

### ISSUE THREAD

**Issue by DCox2016** [lingonsaft/hacktoberfest#651]
Nav links from the helpful-material.html do not working in local dev environment.
Links that are to be fixed.
Home
Contributors
Chesse
Tools
learn!

**Comment by DCox2016** [comment]
I will be taking this issue

**Comment by Broccolai** [comment]
Why did you reopen this?

**Comment by DCox2016** [comment]
It seems that all nav links are broken for local dev. I only fixed the home page and helpful-material.html. If it was a reopen it should not have been it should of been a new PR. Please view gif below to see what I am talking about with the broking links.
![linknotworking](https://user-images.githubusercontent.com/17097992/46491071-aed6aa00-c7d7-11e8-884b-691c0e490557.gif)

**Comment by Broccolai** [comment]
Ah okay, I assumed you fixed all of them in your last pull request.

**Comment by richie-south** [comment]
@DCox2016 Can you or any one confirm that this is fixes or still an issue. Closing this until answered 👍
