### ISSUE TITLE
Bad merge

### ISSUE THREAD

**Issue by Broccolai** [lingonsaft/hacktoberfest#698]
Someone hasn't merged correctly and theres tons of double content and bugs on the site now, I'm taking the home page but other people need to fix the others

**Comment by Broccolai** [comment]
index page fixed with #700

**Comment by CQW-Code** [comment]
I think there's a couple of merges pending--  I just put a pull request in before I saw all the new issues after #571 - I fixed all the broken links in all of the pages on my end (it's the QA Tester in me.... had to play with EVERYTHING...).  We'll see.

**Comment by Broccolai** [comment]
Didn't even notice the broken links, main issue is most of the content repeating 😛

**Comment by CQW-Code** [comment]
I didn't see any duplicates- or not as much as yours lol, as I forgot to fetch  before I sent my stuff up 😛  so missed all the duplicates floating around.

**Comment by Broccolai** [comment]
Helpful materials page is the worst 😮 
<img width="1132" alt="screenshot 2018-10-04 at 22 00 29" src="https://user-images.githubusercontent.com/28634904/46502838-03524780-c821-11e8-8fae-dfc93742523b.png">

**Comment by CQW-Code** [comment]
:-O  That's not what it looked like for me!  there was no big heart.  (Imma gonna go hide now if anyone sees the contributers page I spruced up lol) Red on pink.... horrible for a low vision individual.

**Comment by gagandeepp** [comment]
@richie-south  can I work on this?

**Comment by richie-south** [comment]
@gagandeepp I think we have a couple of pull requests fixing this but they all have conflicts in them right now. But because this is a critical issue you can go ahead and work in it to 👍

**Comment by richie-south** [comment]
We have merged a fix for index.html but are looking for a fix in helpful-material see #718

**Comment by richie-south** [comment]
We have now removed duplication from helpful material #720 Closing this issue now :)
