### ISSUE TITLE
Snek is broken

### ISSUE THREAD

**Issue by alexdriaguine** [lingonsaft/hacktoberfest#730]
The snek game is broken right now, see the image  
![image](https://user-images.githubusercontent.com/8626168/46536246-2e36ad00-c8ae-11e8-8cdd-da67a43fefb0.png)

The Play-button needs to have the class `.snek-play`, since that's what querySelector is looking for.

Could be a good time to add the snek styles to a stylesheet instead of setting them in javascript aswell :)

**Comment by casmith205** [comment]
ill take this one!

**Comment by richie-south** [comment]
@casmith205 Wihoo 👍

**Comment by casmith205** [comment]
https://github.com/lingonsaft/hacktoberfest/pull/740

fixed here

**Comment by BennyCarlsson** [comment]
@casmith205  Great job fixing this :) closing issue 🐍
