### ISSUE TITLE
Navbar "Others" is broken

### ISSUE THREAD

**Issue by BennyCarlsson** [lingonsaft/hacktoberfest#736]
The Others button in navbar is broken

**Comment by juliegoat** [comment]
On it!

**Comment by richie-south** [comment]
@juliegoat Awesome 💛

**Comment by keeganthomp** [comment]
ah, dangit! @juliegoat I just now saw your comment after submitting PR...When I started 30 mins ago there were no dibs. My apologies Julie!!

**Comment by richie-south** [comment]
Could we get it like a hover dropdown that don't change the hight of the nav bar?

**Comment by keeganthomp** [comment]
@richie-south yep! give me 15
