### ISSUE TITLE
Implement the new Design on index.html to the other pages 

### ISSUE THREAD

**Issue by BennyCarlsson** [lingonsaft/hacktoberfest#737]
Starting page have a new look. Update the other page to start matching it.

(Can be small pull request to start looking like it doesn't have to be the whole page)

**Comment by m4tr1k** [comment]
@BennyCarlsson I can do it! Can I just PR a few pages or just one?

**Comment by viveksdf** [comment]
@BennyCarlsson I am also trying to make some design changes

**Comment by BennyCarlsson** [comment]
@m4tr1k @viveksdf both can go ahead and go crazy ;) just remember that bigger pull requests are harder to merge because we get a lot of pull requests :)

**Comment by viveksdf** [comment]
@BennyCarlsson Nothing to change in index.html as its already clean but added a link to my mean stack demo repo. Its okay for a PR right?

**Comment by BennyCarlsson** [comment]
@viveksdf Yeah go ahead. You can add or change almost anything even if there is no issue ;)

**Comment by BennyCarlsson** [comment]
closing this but feel free to keep working on it :)
