### ISSUE TITLE
Weird `options` navigation on contributors page

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#745]
Should be like index.html

**Comment by aniketbiprojit** [comment]
Will look into it.

**Comment by richie-south** [comment]
@aniketbiprojit Great 👍

**Comment by aniketbiprojit** [comment]
@CQW-Code Yeah, they were fixed. The issue has been closed. It still doesn't show drop-down menu for others.

**Comment by CQW-Code** [comment]
Yeah I'm having problems with that- the navbar button won't open anything (using the same as other pages like Tools and Helpful Material).

**Comment by richie-south** [comment]
Looks like we don't have to option menu any more so closing this :)

**Comment by richie-south** [comment]
@CQW-Code I'm sorry you pull request was forgotten or buried :) We get so many pull requests with so many random fixes that we cannot keep track och everything.

**Comment by CQW-Code** [comment]
@richie-south  No worries.. I can see that this is a popular repo/project.  It's happened to me before with losing parts of my code etc- part of learning!
