### ISSUE TITLE
Navigation on contributors page is broken

### ISSUE THREAD

**Issue by Broccolai** [lingonsaft/hacktoberfest#762]
<img width="982" alt="screenshot 2018-10-05 at 18 12 28" src="https://user-images.githubusercontent.com/28634904/46549525-4288a300-c8ca-11e8-9fd9-66a8151064e8.png">

**Comment by CQW-Code** [comment]
I think I fixed this with my pull request- #571 and #701 
#571 #701

**Comment by Broccolai** [comment]
Still looks the same to me 🤔

**Comment by CQW-Code** [comment]
Hmm (I can't find that emoji).  I'd like to take a look again and see if I can fix it; I know Richie-South merged about 30 minutes ago.

**Comment by Broccolai** [comment]
Yeah I know, i hard refreshed the page and tried in on seperate computers / browsers. Maybe it's just me or something to do with the service worker?

**Comment by CQW-Code** [comment]
No idea but I did find that there were some missing closing tags in the contributers.html file. (that may have been me when I was resolving the conflicts).  Working on it right now.

**Comment by richie-south** [comment]
Looks like we don't have an options menu any more so closing this :) :)
