### ISSUE TITLE
Navigation bar cleanup 

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#832]
We only want to keep `home`, `helpful material`, `contributors` and `other` in the navbar then we want to place every other item as a dropdown alternative under `other` 👍 

The menu is written in javascript right now and we would like to keep it that way :)

**Comment by ananthuc73** [comment]
can i pull a request?

**Comment by ananthuc73** [comment]
i will take this

**Comment by BennyCarlsson** [comment]
@ananthuc73 Great go ahead :)

**Comment by ananthuc73** [comment]
ok

**Comment by BennyCarlsson** [comment]
Great work :)
