### ISSUE TITLE
Rearrange videos in index.html

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#833]
We want to place the `Hacktoberfest Intro` video above the two other videos and make it a little larger

**Comment by Cherrytone** [comment]
I'd like to give it a go.

**Comment by richie-south** [comment]
@Cherrytone Okey 👍

**Comment by cTxplorer** [comment]
Apologies, that I started working on the issue without being assigned the task. Just came to know that it has been assigned to someone else.

@richie-south , you could merge @ChameeraD 's PR into the master :)
