### ISSUE TITLE
Sync faq

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#834]
The FAQ in the README.md and index.html is not in sync. Both should have all the questions

**Comment by zedd-08** [comment]
Can I work on this?

**Comment by richie-south** [comment]
@zedd-08 👍

**Comment by Xenos5282** [comment]
ohh man! I already did it... Sorry mate @zedd-08

**Comment by BennyCarlsson** [comment]
Well looks like it's done good job :)
