### ISSUE TITLE
Add social icons 

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#835]
Add social links to our instagram, twitter and youtube in the navbar or in a footer or in a side bar you chose 😉 

Twitter: https://twitter.com/lingonsaft1
Instagram: https://www.instagram.com/lingonsaftofficial/
Youtube: https://youtube.com/lingonsaft

**Comment by cTxplorer** [comment]
@richie-south can I work on this?

**Comment by AnchalJain** [comment]
can I solve this issue?

**Comment by lufunno** [comment]
add me

**Comment by richie-south** [comment]
@lufunno 👍

**Comment by ananthuc73** [comment]
can i pull a request?
