### ISSUE TITLE
Fix helpful-material page

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#837]
It looks kinda fu***d up 

<img width="1412" alt="screen shot 2018-10-06 at 10 12 22" src="https://user-images.githubusercontent.com/8655479/46569084-5971d880-c950-11e8-989f-c0b2b37d66ee.png">

**Comment by yoksanherlie** [comment]
I will try to fix it!

**Comment by richie-south** [comment]
@yoksanherlie Go for it :)

**Comment by AnchalJain** [comment]
Can I fix this?

**Comment by Casey-McCray** [comment]
Can I work on this?

**Comment by BennyCarlsson** [comment]
closing this for now will open again later. Feel free to keep working on it tough ;)
