### ISSUE TITLE
FAQ, last item disappears 

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#85]
Last item of the FAQ list disappears on larger screens and animates in / out all the time on smaller ones 

[GIF OF ISSUE](https://imgur.com/a/gkdeRZF)

**Comment by smokyabdulrahman** [comment]
could you assign me to solve this issue, please?

**Comment by richie-south** [comment]
@smokyabdulrahman Sorry this issue should have been closed almost right after i opened it :)
