### ISSUE TITLE
Some names in contributors.html are not in accordance to the style.

### ISSUE THREAD

**Issue by shubhamcr** [lingonsaft/hacktoberfest#901]
<img width="1680" alt="screen shot 2018-10-06 at 8 14 51 pm" src="https://user-images.githubusercontent.com/20488600/46572501-82bc5400-c9a4-11e8-8e44-546585f110bd.png">

**Comment by shubhamcr** [comment]
Can I fix this ?

**Comment by shubhamcr** [comment]
Please attach label **bug** and **hacktoberfest**

**Comment by Broccolai** [comment]
I'll work on this

**Comment by Broccolai** [comment]
Fixed with #906

**Comment by BennyCarlsson** [comment]
Great work
