### ISSUE TITLE
Change the main colors to match https://lingonsaft.com

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#92]
I like red 🔴

**Comment by arihantbansal** [comment]
Exactly what is to be done?

**Comment by richie-south** [comment]
Right now the main colors of https://hacktoberfest.lingonsaft.com/ are blue (header menu, links?) could we change the colors to match  https://lingonsaft.com/ colors which are red

**Comment by versavale** [comment]
Sure thing! Happy to work on that :)

**Comment by richie-south** [comment]
@versavale Great 👑

**Comment by agampreetsingh** [comment]
Will really be happy to work on the issue! :)

**Comment by mukul-kgp** [comment]
I would like to contribute!

**Comment by richie-south** [comment]
Oo and also i just merged a pull request that changed layout design and also colors to black could we get this to red again? 🔙

**Comment by versavale** [comment]
Yup! On it :) Finished with the navbars, moving on to links. Pull request coming soon!

**Comment by richie-south** [comment]
@versavale Great 😃

**Comment by richie-south** [comment]
Closing this with the power of @versavale pull request 🦀
