### ISSUE TITLE
Cheese page is completely broken

### ISSUE THREAD

**Issue by BennyCarlsson** [lingonsaft/hacktoberfest#946]
https://hacktoberfest.lingonsaft.com/cheese

Need some fixes and maybe styling 🧀

**Comment by SheW0lf** [comment]
oh not a broken cheese page! may I work on this?

**Comment by jakeraffe** [comment]
That is a broken cheese page. Can you assign me to this? Id like to attempt a fix.

**Comment by abisummers** [comment]
I've changed some things- I've updated the ID's to class names since they were for styling and not for linking. And I've fixed some typos :)

**Comment by richie-south** [comment]
Looks like it is still broken

**Comment by albertm805** [comment]
I can work on this.

**Comment by CodeWeeD0** [comment]
https://github.com/lingonsaft/hacktoberfest/pull/1154

can you confirm now whether it is broken or not?

**Comment by Anjibansal** [comment]
Can i work on this issue ?

**Comment by richie-south** [comment]
@Anjibansal Absolutely

**Comment by CodeWeeD0** [comment]
> @CodeWeeD0 It looks a lot better, but there are still things that could be changed on the cheese page

Do you have any prototype design? If yes, i would like to see it. I can assure i'll be able to change the page to be clone of that prototype.

**Comment by jeduardo824** [comment]
Can i work on this issue ?

**Comment by amanjain-aj** [comment]
Cheese Page Has Been Improved. Can you confirm whether it is still broken!!

**Comment by richie-south** [comment]
@amanjain-aj it is vastly improved! But i would not say it is completely fixed :)

**Comment by ibuli** [comment]
#1390 I have updated the whole cheese page and removed unwanted items from the page.
Please have a look

**Comment by ibuli** [comment]
https://hacktoberfest.lingonsaft.com/cheese
Page looks good now.
@richie-south

**Comment by BennyCarlsson** [comment]
Awesome work :)

**Comment by amanjain-aj** [comment]
Thnks
