### ISSUE TITLE
Navbar not working locally

### ISSUE THREAD

**Issue by BennyCarlsson** [lingonsaft/hacktoberfest#995]
The menu doesn't work locally when you open index.html

I want it to work locally without the need of starting a local server

**Comment by frextrite** [comment]
Is there anything else other than 'now' you're using to deploy the site?

**Comment by richie-south** [comment]
@frextrite No we only use now :)

**Comment by jjones09** [comment]
I've put in the above PR to fix this. Works locally for me and seems to be okay on the now deploy

**Comment by richie-south** [comment]
Should be fixed in #1101
