### ISSUE TITLE
Remove The twist from navbar

### ISSUE THREAD

**Issue by BennyCarlsson** [lingonsaft/hacktoberfest#996]
In the navbar under **others** remove **The Twist** button

**Comment by pegasus-lynx** [comment]
I am on it

**Comment by pegasus-lynx** [comment]
Where exactly the change is to be made?

**Comment by BennyCarlsson** [comment]
probably just need to be removed from https://github.com/lingonsaft/hacktoberfest/blob/master/menu.json

**Comment by BennyCarlsson** [comment]
Great it's fixed now :)
