### ISSUE TITLE
Helpful-material footer

### ISSUE THREAD

**Issue by BennyCarlsson** [lingonsaft/hacktoberfest#999]
The footer in the helpful-material page doesn't really match the other pages. Style it or change it?

**Comment by frextrite** [comment]
Doesn't match with the rest of the website. Maybe not make it floating?

**Comment by BennyCarlsson** [comment]
that would be a good start yes :)

**Comment by alekangelov** [comment]
@BennyCarlsson can I take this issue on? 😅

**Comment by alekangelov** [comment]
@BennyCarlsson mind me taking this issue on? 😄

**Comment by pfistersimon** [comment]
need still help at this issue

**Comment by meyfleur** [comment]
do you still need help with that?

**Comment by richie-south** [comment]
Closing this issue and opening a new similar one :)
